// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFhb9aysrzPAUdBydu4Z8Own_OEnTnas',
    appId: '1:933662549011:web:a06bad719eab40239ccbe6',
    messagingSenderId: '933662549011',
    projectId: 'fir-clean-6ed6c',
    authDomain: 'fir-clean-6ed6c.firebaseapp.com',
    storageBucket: 'fir-clean-6ed6c.firebasestorage.app',
    measurementId: 'G-MNZJZ20TFX',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJFhb9aysrzPAUdBydu4Z8Own_OEnTnas',
    appId: '1:933662549011:web:a06bad719eab40239ccbe6',
    messagingSenderId: '933662549011',
    projectId: 'fir-clean-6ed6c',
    authDomain: 'fir-clean-6ed6c.firebaseapp.com',
    storageBucket: 'fir-clean-6ed6c.firebasestorage.app',
    measurementId: 'G-MNZJZ20TFX',
  );
}
