// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyrKk2ZBWPGSZ-bJQmMZoTchbLjw6Olgo',
    appId: '1:718127856617:web:f5d0fbe948f049171c6978',
    messagingSenderId: '718127856617',
    projectId: 'daimound-clean',
    authDomain: 'daimound-clean.firebaseapp.com',
    storageBucket: 'daimound-clean.firebasestorage.app',
    measurementId: 'G-MLSNEP423X',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyrKk2ZBWPGSZ-bJQmMZoTchbLjw6Olgo',
    appId: '1:718127856617:web:43de9f132f98cdec1c6978',
    messagingSenderId: '718127856617',
    projectId: 'daimound-clean',
    authDomain: 'daimound-clean.firebaseapp.com',
    storageBucket: 'daimound-clean.firebasestorage.app',
    measurementId: 'G-BC91VW8GEH',
  );
}
